### ISSUE TITLE
[FEATURE REQUEST] Shorten die chatgames questions

### ISSUE THREAD

**Issue by christinloehner** [TectHost/TChat#13]
In the chatgames.yml, there are 77 lines needed for one single question.

Please make most of the options "defaultable". That means, under the keyword "games:" there should not only be "game1:" to "game1000:", but also all of the options and effects as defaults. So that in the "games1:" section, you only have these keywords:

```
  game1:
    enabled: true
    messages:
      - "%center%&#44d742&lQuizz Zeit!"
      - "%center%&7In welchem Gebirge liegt der Mount Everest?"
    keywords:
      - "Himalaya"
      - "himalaya"
```

All other options should we able to make them as default for all questions.

(Sorry for my bad english)
