### ISSUE TITLE
problem with the upgrade

### ISSUE THREAD

**Issue by jumento** [TectHost/TChat#4]
_(The bug is only when you make a upgrade)_
if you have a old version and you upgrade to the new version 3.3.7  you can't access to the new features:

Added sounds on join
Added titles on join

because the file config there was not update you need added the nex code: 

```
Particles:
    Join:
      joinParticlesEnabled: true
      # Particles:
      # - FLAME
      # - CLOUD
      # You can suggest more particles in the discord server!
      joinParticlesType: "FLAME"
    Quit:
      quitParticlesEnabled: true
      # Particles:
      # - FLAME
      # - CLOUD
      # You can suggest more particles in the discord server!
      quitParticlesType: "CLOUD"
  Sounds:
    Join:
      joinSoundEnabled: true
      joinSoundType: "ENTITY_PLAYER_LEVELUP"
    Quit:
      quitSoundEnabled: true
      quitSoundType: "ENTITY_GENERIC_EXPLODE"
  # Titles are only sent to the player who enters, not to all players
  Titles:
    enabled: true
    title: "&5Welcome to the server!"
    subtitle: "&5TChat &e- &5Tect.host"

```
