### ISSUE TITLE
[SUGGESTION] WRITE MESSAGES TO CHANNELS

### ISSUE THREAD

**Issue by HonzasikCZ** [TectHost/TChat#5]
Make it possible to write directly to the channel via a single command.
For example: /staffchat Hello!

**Comment by Tect-host** [comment]
I just added for 4.0.4 the command /channel send (channel) (message)
Using the custom commands you can do what you said, here is an example:

```yaml
staffchat:
    permission-required: false
    args: true
    cooldown: 0
    actions:
      - "[PLAYER_COMMAND] channel send staffchat %args%"
```
